# For ARIMA Model 
(data <- scan ("ARIMADataset.txt", skip = 1)) 
ts.plot(data) 
par (mfrow=c(1,2)) 
acf(data, lag.max=100) 
pacf(data, lag.max=100) 
diffdatal = diff(data, 1, 1) 
ts.plot(diffdatal, xlim = c(0, 100), ylim=c(-15, 15)) 
acf(diffdatal, lag.max=100) 
pacf(diffdatal, lag.max=100) diffdata2 = diff(data, 1, 2) 
ts.plot(diffdata2, xlim = c(0, 100), ylim=c(-15, 15)) 
par (mfrow=c(1,2)) 
(acf(diffdata2, lag.max=100)) 
(Vhat1<-1+(2* (0.174^2+1^2))) 
(Vhat2<-1+(2*(-0.391^2+0.174^2+1^2))) 
(Vhat3<-1+(2*(-0.205^2+-0.391^2+0.174^2+1^2))) 
(Vhat4<-1+(2* (0.076^2+-0.205^2+-0.391^2+0.174^2+1^2))) 
(Vhat5<-1+ (2* (0.118^2+0.076^2+-0.205^2+-0.391^2+0.174^2+1^2))) 
sqrt(vhat1)/10 
sqrt(Vhat2)/10 
sqrt(vhat3)/10 
sqrt(Vhat4)/10 
sqrt(Vhat5)/10 
(z1<- 0.174/0.1749443) 
(Z2<- (-0.391)/0.1659756) 
(Z3<- (-0.205)/0.163424) 
(Z4<- 0.076/0.163777) 
(Z5<- 0.118/0.164625) 
(pacf(diffdata2, lag.max=100)) 
VAR.MEAN (diffdata2) 
SEACF (diffdata2, 10, 10) 
(fit1 = arima(data, order = c(0,2,2), method = "ML")) 
summary (fit1) 
(Residuals<-fit1$residuals)
ts.plot(Residuals) 
par (mfrow=c(1,2)) 
acf(Residuals) 
acf(Residuals, type="p") 
SEACF (Residuals,K=5,L=5) 
par(mfrow=c(3,1)) 
hist(Residuals) 
qqnorm(Residuals)
qqline (Residuals)
plot(density(Residuals)) 
shapiro.test(Residuals) 
library(tseries) 
jarque.bera.test(Residuals) 
ks.test(Residuals, "pnorm", mean=mean(Residuals), sd=sqrt(var(Residuals)) 
PORT.TEST(100, Residuals, 10) 
PORT.TEST(100, Residuals, 12) 
PORT.TEST(100, Residuals, 14) 
#### 
(fit2 = arima (data, order = c(2,2,0), method = "ML")) 
summary(fit2) 
(Residuals<-fit2$residuals) 
ts.plot(Residuals) 
par(mfrow=c(1,2)) 
acf(Residuals) 
acf(Residuals, type="p") 
SEACF(Residuals, K-5, L=5) 
hist(Residuals) 
qqnorm(Residuals)
qqline (Residuals) 
plot(density(Residuals)) 
shapiro.test(Residuals) 
library(tseries) 
jarque.bera.test(Residuals) 
ks.test(Residuals, "pnorm", mean=mean (Residuals), sd=sqrt(var(Residuals)) 
PORT.TEST(100, Residuals, 10) 
PORT.TEST(100, Residuals, 12) 
PORT.TEST(100, Residuals, 14) 
#### 
(fit2 = arima (data, order = c(2,2,0), method = "ML")) 
summary (fit2) 
(Residuals<-fit2$residuals) 
ts.plot(Residuals) 
par(mfrow=c(1,2)) 
acf(Residuals) 
acf(Residuals,type="p") 
SEACF(Residuals,K=5,L=5) 
hist(Residuals) 
qqnorm(Residuals)
qqline(Residuals) 
plot(density(Residuals)) 
shapiro.test(Residuals) 
library(tseries) 
jarque.bera.test(Residuals) 
ks.test(Residuals,"pnorm", mean=mean(Residuals), sd=sqrt(var(Residuals) 
PORT.TEST(100, Residuals, 10) 
PORT.TEST(100, Residuals, 12) 
PORT.TEST(100, Residuals, 14) 
# For SARIMA Model 
library(forecast) 
(data <- scan ("SARIMAData.txt",skip=1)) 
data.ts<-ts (data, start = c(1964,1), end = c(1972,9),frequency 
             ts.plot(data, col="royalblue",xlab = "Time", ylab = "Perrin Freres monthly champagne sales") 
data <- log(data.ts) 
par(mfrow=c(1,2)) 
acf(data, lag.max=100) 
pacf(data, lag.max=100) 
diffdatal = diff(data, 1, 12) 
ts.plot(diffdatal, col="royalblue",xlab = "Time",ylab = "Perrin Freres monthly champagne sales") 
acf(diffdatal, lag.max=100) 
pacf(diffdatal, lag.max=100) 
diffdata2 = diff(diff(data, lag = 12, diff = 1))=12) 
ts.plot(diffdata2, col="royalblue",xlab = "Time",ylab = "Perrin Freres monthly champagne sales") 
par(mfrow=c(1,2)) 
acf(diff(diff(data, lag = 12, diff = 1)), lag.max=100, type = "p") 
a<-pacf(diff(diff(data, lag = 12, diff = 1)), lag.max=100) 
SEACF(diff (diff(data, lag = 12, diff = 1)),10,10) 
VAR.MEAN(diffdata2) 
(fitlarima(data,order = c(3,1,0),summary(fitl)))
seasonal = list(order(Residuals<-fit1$residuals) 
ts.plot(Residuals) 
par(mfrow=c(1,2)) 
acf(Residuals) 
acf(Residuals, type="p") 
SEACF (Residuals, K-5, L=5) 
par(mfrow=c(3,1)) 
hist(Residuals) 
qqnorm(Residuals)
qqline (Residuals)
plot(density(Residuals))=c(1,1,1),period=12),method="ML")) 
ks.test(Residuals, "pnorm",mean=mean(Residuals),sd=sqrt(var(Residuals))) 
PORT.TEST(100,Residuals,10) 
PORT.TEST(100, Residuals, 12) 
PORT.TEST(100, Residuals, 14) 
(fit2 = arima (data, order = c(0,1,1),summary(fit2)))
seasonal=list(order = c(1,1,1), period = 12), method = "ML")) 
(Residuals<-fit2$residuals) 
ts.plot(Residuals) 
par(mfrow=c(1,2)) 
acf(Residuals) 
acf(Residuals, type="p") 
SEACF(Residuals, K=5, L=5) 
par(mfrow=c(3,1)) 
hist(Residuals) 
qqnorm(Residuals)
qqline(Residuals) 
plot(density(Residuals)) 
ks.test(Residuals,"pnorm", mean=mean(Residuals),sd=sqrt(var(Residuals))) 
PORT.TEST(100, Residuals, 10) 
PORT.TEST(100, Residuals,12) 
PORT.TEST(100, Residuals, 14)